<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\NzyteTv.Core\NzyteTv.Core.csproj" />
    <ProjectReference Include="..\NzyteTv.Media\NzyteTv.Media.csproj" />
    <ProjectReference Include="..\NzyteTv.Operations.Contracts\NzyteTv.Operations.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>nzytetv-dashboard</AssemblyName>
    <VersionPrefix>0.3.0</VersionPrefix>
    <VersionSuffix>3b3-b2c</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NzyteTv.Dashboard.Tests" />
  </ItemGroup>

</Project>
